//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class component
    {
        public long Id { get; set; }
        public long Type { get; set; }
        public long Warehouse { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public long Provider { get; set; }
        public Nullable<long> Order { get; set; }
    
        public virtual Order Order1 { get; set; }
        public virtual Provider Provider1 { get; set; }
        public virtual Type Type1 { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
